system:
  ip:
  port: 9090
  env: dev
log:
  app: server
  dir: Logs
db:
  host: localhost
  port: 5432
  user: postgres
  password: yourpassword
  dbname: yourname
  sslmode: disable
onnx:
  model_path: models/model.onnx
  input_size: 128
